### ISSUE TITLE
chore: Remove unnecessary react imports

### ISSUE THREAD

**Issue by 0xMirim** [0xMirim/ape-tax#5]
Directly importing react used to be required but for a while now it hasn't been (Reference: [The New JSX Transform](https://legacy.reactjs.org/blog/2020/09/22/introducing-the-new-jsx-transform.html)).

This means we can clean things up by removing all direct imports of React from 'react'

So when we see something like:

- `import React, {useEffect, useState} from 'react';`

could be changed to...

- `import {useEffect, useState} from 'react';`

without causing any error of loss of functionality

Any line that is only `import React from 'react';` should be removed completely

**Comment by Itzabelli** [comment]
PR with these changes were sent to the saltyfacu/ape-tax repo.
